---
title: "git_01"
author: "Kathleen Giba"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  In winter, when the fields are white,  
I sing this song for your delight.  
In Spring, when woods are getting green,  
I’ll try and tell you what I mean.  
In Summer, when the days are long,  



## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Quick!   quick!  
    The cat's been sick.  

Where?   where?  
    Under the chair.  

Hasten!   hasten!  
    Fetch the basin.  

Alack!   alack!  
    It is too late,  
The carpet's in  
    An awful state.  

No!   no!  
    It's all in vain,  
For she has licked it  
    Up again.  
    